### ISSUE TITLE
cmake policy CMP0042 doesn't exist in cmake version 2.8.1

### ISSUE THREAD

**Issue by sfod** [Cylix/cpp_redis#10]
There is a little inconsistency in CMakeLists.txt in these lines:
```
cmake_minimum_required(VERSION 2.8.1)
cmake_policy(SET CMP0042 NEW)
```

Problem is CMP0042 was introduced in CMake version 3.0 (https://cmake.org/cmake/help/v3.0/policy/CMP0042.html)

Probably the easiest solution is to set minimum required version of CMake to 3.0.

But I've encountered this problem on Ubuntu 14.04, where default CMake verison is 2.8.12.
To fix CMake errors I've replace the first two commands with following:
```
cmake_minimum_required(VERSION 2.8.12)
set(CMAKE_MACOSX_RPATH 1)
```

**Comment by Cylix** [comment]
Hi,

Thank you for noticing me about that, you are absolutely right.
I made the modification using your suggestion.

Thanks again!
