### ISSUE TITLE
Unresolved symbols WSAStartup, WSACleanup

### ISSUE THREAD

**Issue by pembeci** [Cylix/cpp_redis#102]
I followed the instructions for using the library on Windows (Win7, Visual Studio 2015, cMake 3.9). I needed to use the `-DMSVC_RUNTIME_LIBRARY_CONFIG=/MD` option. When I tried the example given in the wiki I am getting the following error though:

![redis_err](https://user-images.githubusercontent.com/2614837/29808725-e9c96bb0-8ca1-11e7-8924-f4ef85e98002.jpg)

Is this a configuration issue? I used the default Debug/Win32 configuration when I was building `cpp_redis` on VS and my test project is using the same. Thanks.

**Comment by Cylix** [comment]
Hi,

Did you link your program with `Ws2_32.lib`?
Both `WSAStartup` and `WSACleanup ` are part of the windows standard network library.

I will update the wiki to make it clearer though.

Let me know if it fixes this issue :)

Best

**Comment by pembeci** [comment]
Yep, that was it. I guessed it was a linkage issue but it has been a while I build C++ code in Windows so I wasn't sure where to look. Thanks @Cylix.

**Comment by pembeci** [comment]
I [added](https://github.com/Cylix/cpp_redis/wiki/Examples/_compare/bc867472c071c5ab65b349c387101c47a67bda69...814b5cea341305476c7df200b3a4c08f5e01f1f1) my pragma directive solution to the wiki examples. It works in Visual Studio. I can revert it if you didn't like it.
