### ISSUE TITLE
about access redis cluster

### ISSUE THREAD

**Issue by 7zkeeper** [Cylix/cpp_redis#104]
how can i use redis cluster with the project if i dont use proxy like twemproxy

**Comment by Cylix** [comment]
Hi,

You might find the information you are looking for in #84.

Basically, there is no support for clusters in cpp_redis.
It is possible to use cpp_redis to call the Redis cluster control related functions (cluster_*), but there is no special handling for clusters themselves. It would be up to you to code a wrapper around cpp_redis to do what you are looking for.

There is apparently an increasing demand concerning cluster support, so I am more and more considering to provide such support in the future, but I lack time for now and I have no plans/deadlines for that.

Please let me know if you have any other questions,

Best!
