### ISSUE TITLE
Any support for ReJSON module from this client

### ISSUE THREAD

**Issue by badarihp** [Cylix/cpp_redis#105]
Hi I am new to this client and for my application I was looking out for high through put client which can work with Redis cluster configuration.
And was interested to know if this client supports ReJSON module https://github.com/RedisLabsModules/ReJSON

**Comment by Cylix** [comment]
Hi,

I did not know about ReJSON module, so there is actually no official support for it.
I'm not sure about how ReJSON work, but seems like it is mostly a server-side module that provides additional commands to manipulate JSON objects.

If so, then you can still use cpp-redis to communicate with your server configured with ReJSON by using the `.send()` member-function of the `redis_client`.
The `.send()` function allows you to pass raw commands directly. Though not as handy as the existing wrapper functions (like get, set, incr, ...), `send` is flexible and basically allows you to send any command of your choice to the server.

For example:
```cpp
cpp_redis::redis_client client;
client.send({ "JSON.GET", "doc", ".foo" }, [] (cpp_redis::reply& reply){
   //! do whatever you want with the reply
});
client.commit();
# or client.sync_commit();
```

I might add some wrappers for these commands later, but I currently have more important tasks to complete first, but you are welcome to submit a PR if you happen to have the time :)

Best!

**Comment by badarihp** [comment]
Thanks for the information
