### ISSUE TITLE
commit in example seems redundant

### ISSUE THREAD

**Issue by prehistoric-penguin** [Cylix/cpp_redis#106]
The `commit ` statement here seems redundant, I have removed [this line](https://github.com/Cylix/cpp_redis/blob/master/examples/future_client.cpp#L59) and the code runs ok.

And I just went through the code , I found the command already called `commit` in `exec_cmd`.

**Comment by Cylix** [comment]
Hi,

Thanks for reporting this issue :)
This is indeed a typo in the code. I already noticed it is fixed on my development version which will be released as soon as #101 is merged (this will be a major release, technically this weekend or next week).
The fix will remove the call to .commit inside exec_cmd such that you need to call commit on your side to flush the pipelined commands as expected.

Please let me know if you have any other questions.

Best,
