### ISSUE TITLE
tag v4?

### ISSUE THREAD

**Issue by sweetim** [Cylix/cpp_redis#111]
Currently, the latest version is v4? but it is not tag?

There are few breaking changes for upgrading from v3.5.4, which is highlighted at the changelog
https://github.com/Cylix/cpp_redis/blob/master/CHANGELOG.md#v400

**Comment by Cylix** [comment]
Indeed you are right!
I was pretty sure I drafted a release but seems like I didn't.

I just published one!

Thanks for noticing me about that and let me know if you have any other concerns :)

Best
