### ISSUE TITLE
how use the get/set

### ISSUE THREAD

**Issue by wenhuancai** [Cylix/cpp_redis#125]
I read the documentation.I know I can pass the string through get/set, but how do I pass the binary?(bitcount?
For example: I call hset to pass a structure.How do I type or take out?

thank you!
I'm not very good at English.So I need more examples.Thank you very much for your answer to the last VS2015 compilation question. Thank you.

**Comment by Cylix** [comment]
Hi,

get/set take an std::string as a parameter as you noticed
However, std::string, supports binary data, leading to get/set supporting binary data too.

For example, you can set the following binary data in this way:

```cpp
  std::vector<char> binary = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
  client.set("hello", {binary.begin(), binary.end()});
```

Here I just have a vector of char and use it to initialize my std::string with binary data.
This is one way to initialize an std::string with binary data, but there are plenty of other ways (and you can use vectors of other types, such as int vectors).

Also note that in my example, the first element is 0: normally, that should be interpreted as a null byte, so the end of a string. But when initializing an std::string that way, 0 is not interpreted as a null-byte, but simply as binary data.

This set data can then be retrieved with a get:

```cpp
  client.get("hello", [](cpp_redis::reply& reply) {
      for (unsigned int i = 0; i < reply.as_string().size(); ++i) {
      	std::cout	<< "get hello[" << i << "]: " << (int)reply.as_string()[i] << std::endl;
      }
  });
```

This will produce the following output:

```
get hello[0]: 0
get hello[1]: 1
get hello[2]: 2
get hello[3]: 3
get hello[4]: 4
get hello[5]: 5
get hello[6]: 6
get hello[7]: 7
get hello[8]: 8
get hello[9]: 9
get hello[10]: 10
```

Thus, we were able to store binary data and retrieve it.

Let me know if you have any other questions (do not hesitate to re-open this issue if necessary).

Best!

**Comment by wenhuancai** [comment]
64/5000  
Your reply has helped me a lot. I have read your code and I have learned c++ 11. Thank you very much. I am developing with your redis, and I have questions for you. Thank you again! # #

**Comment by Cylix** [comment]
Hi,

Glad that this library brought you satisfaction!
If you have any question, feel free to ask here.

Best
