### ISSUE TITLE
Changing the number of IO workers stops all of them.

### ISSUE THREAD

**Issue by orlinhristov** [Cylix/cpp_redis#126]
Hi  Cylix,

First of all thanks for the great lib!

The cpp_redis::client doesn't have any method that can be used to set the number of io_service workers. I tried to "workaround" it by creating the client with an instance cpp_redis::network::tcp_client, but I found, that soon after the client was created all the workers have gone. The reason was that the cpp_redisget_default_io_service(std::uint32_t num_io_workers) was called from the library, passing the default argument (1) and the workers was reset, even the io_service_default_instance was already created. I see a couple of problems here:
* By my opinion, the parameter should be used to construct the instance. If it was already created, then the number of workers should not be changed. If you want to change the number of workers, it could be done as follow:

`tacopie::get_default_io_service()->set_nb_workers(N);`

* The other problem is that decreasing the number of workers actually stops all of them, which for me looks like a bug.

Regards,
Orlin Hristov.

**Comment by Cylix** [comment]
Hi @orlinhristov ,

Glad that you appreciate cpp_redis and apologize for the late reply as I was traveling from France to California recently.

That definitely sounds like a bug. I haven't tried to reproduce it yet, but I'll try to dig into it and fix it as soon as I can.

Thanks for reporting this issue, that helps me to make cpp_redis better and better over the time :)

Best!

**Comment by Cylix** [comment]
FYI, working on it, will be fixed by tmr.

**Comment by Cylix** [comment]
Hi,

This issue has been fixed (fix deployed on master)

* get_default_io_service does not take any parameter anymore. It makes the usage less error-prone and fix the reset you reported
* shrinking the number of workers does not remove all of them anymore (bug fixed)

I'm closing this issue but do not hesitate to re-open it if there is any other issues post-fix!

Thanks again for reporting the issue,

Best
