### ISSUE TITLE
Connection timeout_msecs different from 0 results in failed connection

### ISSUE THREAD

**Issue by Alejandro131** [Cylix/cpp_redis#132]
Hi Cylix,

Thank you for the previous updates and support of the library! I hope that this doesn't become a usual thing as on one side it is good for you to be able to improve your library, but on the other side most people don't like fixing bugs and having many issues in their repositories :D

As the title of the issue suggests, when trying to establish a connection to a redis node (no matter of its type - redis or sentinel) if the timeout_msecs is different from 0, a connection cannot be established and after the time expires, an exception is thrown:

```
terminate called after throwing an instance of 'cpp_redis::redis_error'
  what():  connect() timed out
```

I actually found this issue not while trying to use the normal redis client, but rather when trying to connect to a sentinel. After adding sentinels to the configuration and trying to get a master host and port it iterates through the list of sentinels and tries to connect to each of them with a timeout of 2 seconds. I was getting an exception that no master by the name specified could be found, but after some digging underneath it, it was actually the timeout problem. Since it involves a redis connection and it doesn't matter what type it is, here is a reproducible code snippet:

```
#include <cpp_redis/cpp_redis>
#include <iostream>

using namespace std;

int main(void) {
  cpp_redis::client redis;

  uint32_t timeout_msecs = 10000;
  //timeout_msecs = 0;

  redis.connect("127.0.0.1", 6379, nullptr, timeout_msecs);
  redis.select(0);
  redis.sync_commit();

  auto res = redis.get("test");
  redis.sync_commit();

  cout << redis.is_connected() << " get " << res.get() << endl;

  return 0;
}
```

If the timeout is 0, it always connects (around several ms because it is a local connection), but even if it is 10000 (10 seconds) it just waits for them to pass and throws the exception.

The operating system I am on (if it matters) is Ubuntu 16.04 and if you need any further information (if you can't reproduce it) I would be happy to help.

Also even after the bug is fixed, I would like to be able to control the connection timeout for sentinels (if possible), since in certain cases we would like to be able to iterate more quickly through them, while in others a connection might take more time.

Best Regards,
Alex

**Comment by Cylix** [comment]
Hi @Alejandro131 ,

Thanks for reporting this issue: there was a bug in tacopie where the parameters passed to `select()` to poll the connection in case of specified timeout were wrong.

The fix is now pushed and it works on my side. Let me know if it is good for you too if you happen to try the fix :)

Concerning your request for the sentinels, can you let me know more exactly what you are looking for?
If I add a getter in the client/subscriber to get a list of the sentinels and a setter in the sentinel class to set the connection timeout, is it fine for you or you are looking for something else?

Best

**Comment by Alejandro131** [comment]
Hi Cylix,

Just downloaded and compiled the updated version - the problem is gone, thank you for the quick fix!

As for the sentinels, the methods that you suggest are exactly what I'm looking for, so I will download the update once you add them :)

Best Regards,
Alex

**Comment by Cylix** [comment]
Adding the following changes:

In `client`, `subscriber` and `sentinel`, `add_sentinel` now takes an extra optional parameter timeout_msecs that defines connection timeout in msecs for that particular sentinel

 In `sentinel`, there are now two getters `get_sentinels` (const and non-const) returning the list of added sentinels (vector<sentinel_def>). That implies to pass the `sentinel_def` inner class into public and to add an extra getter `get_timeout_msecs` and setter `set_timeout_msecs`.

`get_master_addr_by_name` in `sentinel` is now based on user-defined timeout (each sentinel can have a different timeout)
`connect_sentinel` in sentinel has been changed: it does not take any timeout as parameter: instead, it uses the user-defined timeout (each sentinel can have a different timeout).

This is waiting for CI build, then will be merged.
doxygen doc will be updated once merged.

Let me know if there are some changes you would like me to improve though.

Best!

**Comment by Alejandro131** [comment]
Thank you for the quick update!

I looked at the code and everything seems good. If I have any questions or issues, I will contact you.

Best!

**Comment by Cylix** [comment]
Cool! It has been merged into master FYI.
