### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by huanncbg** [Cylix/cpp_redis#133]
Hi Cylix. I've just update to latest version of cpp_redis on github following compilation instruction.
git 

# git clone https://github.com/Cylix/cpp_redis.git
# cd cpp_redis
# git submodule init && git submodule update
# cmake . && make

After that I received the these error messages.
I'd tried some recent versions of tacopie on github of your but it's still can't compile.
Thanks.

/home/centos/Experiments/cpp_redis/cpp_redis/sources/network/tcp_client.cpp: In member function ‘virtual void cpp_redis::network::tcp_client::connect(const string&, uint32_t, uint32_t)’:
/home/centos/Experiments/cpp_redis/cpp_redis/sources/network/tcp_client.cpp:32:45: error: no matching function for call to ‘tacopie::tcp_client::connect(const string&, uint32_t&, uint32_t&)’
   m_client.connect(addr, port, timeout_msecs);
                                             ^
/home/centos/Experiments/cpp_redis/cpp_redis/sources/network/tcp_client.cpp:32:45: note: candidate is:
In file included from /usr/local/include/tacopie/network/tcp_server.hpp:33:0,
                 from /usr/local/include/tacopie/tacopie:32,
                 from /home/centos/Experiments/cpp_redis/cpp_redis/includes/cpp_redis/network/tcp_client.hpp:28,
                 from /home/centos/Experiments/cpp_redis/cpp_redis/sources/network/tcp_client.cpp:24:
/usr/local/include/tacopie/network/tcp_client.hpp:63:8: note: void tacopie::tcp_client::connect(const string&, uint32_t)
   void connect(const std::string& addr, std::uint32_t port);
        ^
/usr/local/include/tacopie/network/tcp_client.hpp:63:8: note:   candidate expects 2 arguments, 3 provided
/home/centos/Experiments/cpp_redis/cpp_redis/sources/network/tcp_client.cpp: In member function ‘void cpp_redis::network::tcp_client::set_nb_workers(std::size_t)’:
/home/centos/Experiments/cpp_redis/cpp_redis/sources/network/tcp_client.cpp:48:12: error: ‘class tacopie::tcp_client’ has no member named ‘get_io_service’
   m_client.get_io_service()->set_nb_workers(nb_threads);
            ^
/home/centos/Experiments/cpp_redis/cpp_redis/sources/network/tcp_client.cpp: In function ‘void cpp_redis::network::set_default_nb_workers(std::size_t)’:
/home/centos/Experiments/cpp_redis/cpp_redis/sources/network/tcp_client.cpp:86:65: error: too many arguments to function ‘const std::shared_ptr<tacopie::io_service>& tacopie::get_default_io_service()’
   tacopie::get_default_io_service(__CPP_REDIS_LENGTH(nb_threads));
                                                                 ^
In file included from /usr/local/include/tacopie/tacopie:31:0,
                 from /home/centos/Experiments/cpp_redis/cpp_redis/includes/cpp_redis/network/tcp_client.hpp:28,
                 from /home/centos/Experiments/cpp_redis/cpp_redis/sources/network/tcp_client.cpp:24:
/usr/local/include/tacopie/network/io_service.hpp:137:36: note: declared here
 const std::shared_ptr<io_service>& get_default_io_service(void);

**Comment by Cylix** [comment]
Hi,

This is an error that apparently arises when upgrading cpp_redis since there have been quite huge changes during the past few months.

As reported in #116, it seems like there is a conflict between the headers already installed on your systems and the one that should be used to compile (the include directory of the repo).

Apparently, it is using /usr/local/include/tacopie which, I guess, is an older version of tacopie (probably same issue with cpp_redis?).

Can you try to remove /usr/local/include/tacopie and /usr/local/include/cpp_redis and recompile?
You might also try to remove libtacopie.a from /usr/local/lib if it is installed on your system.

Let me know if it solves (or doesn't solve your issue).

Best!

**Comment by huanncbg** [comment]
Hi.
Thanks for reply.
I’ve seen that there was an older version of tacopie installed at /usr/local/include.
I removed it and compile successfully.

Thanks & Best Reguards.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Cylix** [comment]
awesome, thanks!
