### ISSUE TITLE
No High-Availability example

### ISSUE THREAD

**Issue by dkourilov** [Cylix/cpp_redis#135]
The examples page includes "high-availability" example which is simply a redis client example without sentinel: 
https://github.com/Cylix/cpp_redis/wiki/Examples#high-availability

**Comment by Cylix** [comment]
Hi,

Thanks for reporting this, I'm working on this and the example will be updated by tmr.

Best

**Comment by Cylix** [comment]
Hi,

The example has been updated, in both the wiki and source code.

I'm closing this issue but do not hesitate to re-open it if you find any other issues I can assist you with.

Best!

**Comment by dkourilov** [comment]
Thanks very much!
