### ISSUE TITLE
__CPP__REDIS_USE_CUSTOM_TCP_CLIENT build Error with no tacopie !

### ISSUE THREAD

**Issue by wujunjenny** [Cylix/cpp_redis#136]
1.should add #ifndef __CPP__REDIS_USE_CUSTOM_TCP_CLIENT for every tacopie include
2.sentinel with no default construct error 
3.sentinel.hpp and subscriber.hpp miss atomic include

**Comment by Cylix** [comment]
Hi,

Thanks for reporting this issue, all the points listed here make sense and a fix will be pushed soon!

Best

**Comment by Cylix** [comment]
fixed and pushed on master
