### ISSUE TITLE
linking cpp_redis to a shared library

### ISSUE THREAD

**Issue by HongxuChen** [Cylix/cpp_redis#142]
It seems that both `cpp_redis` and `tacopie` are compiled without `-fPIC`, which makes it impossible to compile them into a shared library. Can you provide an option to compile PIC enabled static libraries? Or generate shared libraries as well rather than only provide static ones?

**Comment by PerduGames** [comment]
I think this is being a problem for me as well, that I can not link. When I try I get errors like:

`cpp: 5: undefined reference to `cpp_redis :: client :: client () '`

**Comment by Cylix** [comment]
Hi,

I'll have a look tonight and will keep you up to date!

Best

**Comment by Cylix** [comment]
Hi,

I now compile with the `POSITION_INDEPENDENT_CODE` in the CMake (which basically sets the fPIC option) (f390eef447a62dcb6da288fb1e91f25f8a9b838c).

I'm closing this issue but do not hesitate to re-open it if the problem still persists.

Best

**Comment by HongxuChen** [comment]
@Cylix Can you check whether `tacopie` also needs this property since when I myself change both projects' PIC properties in their CMakeLists.txt files, my shared library still cannot compile correctly (I might be wrong since it may link to the old `tacopie` library)?

**Comment by Cylix** [comment]
I also added the flag to the tacopie CMakeLists. If even by removing any previous tacopie installation, rebuilding and relinking you still have the issue, I'll further investigate.
If you have any compilation logs, do not hesitate to post them here as it may help.
Thanks!

**Comment by HongxuChen** [comment]
@Cylix It works now, thanks so much!
