### ISSUE TITLE
show values of hscan

### ISSUE THREAD

**Issue by tilmanotto** [Cylix/cpp_redis#146]
Hi Cylix,

I'm trying to loop through the result set of a hscan. The size of reply is always two (also with three and more records). The first one is a "0", the second one contains all values concatenated in one string (like key1value1key2value2key3value3). Is there a way to separate the key-value pairs or get a raw output, which I can process on myself?

client->hscan(key, 0, pattern, [&](reply & records) {
  cout << records << endl;
});

Regards,

Tilman

**Example console output**

keys in hash map movies:
impossible1 => mission1
impossible2 => mission2
impossible3 => mission3

```
hscan movies 0 match "im*"
1) "0"
2) 1) "impossible1"
   2) "mission1"
   3) "impossible2"
   4) "mission2"
   5) "impossible3"
   6) "mission3"
```

**Comment by tilmanotto** [comment]
Solution found: 

```
std::map<string, string> result;

 scl->hscan(key, 0, pattern, [&result] (reply & rp) {
     vector<reply> rpArr = rp.as_array();
      for (unsigned int i = 0; i < rpArr.size(); i += 2) {
         result[rpArr[i].as_string()] = rpArr[i + 1].as_string();
      }
 });

```

**Comment by Cylix** [comment]
Awesome!
Sorry that I could not answer on time, but happy you could find a solution.

I'm closing this issue but do not hesitate to re-open it if you feel the need.

Best

**Comment by tilmanotto** [comment]
Doesn’t matter 😊. Your response time is incredibly fast, faster than an any company!

 

Von: Simon Ninon [mailto:notifications@github.com] 
Gesendet: Montag, 11. Dezember 2017 22:29
An: Cylix/cpp_redis <cpp_redis@noreply.github.com>
Cc: tilmanotto <t.otto@varendo.de>; Author <author@noreply.github.com>
Betreff: Re: [Cylix/cpp_redis] show values of hscan (#146)

 

Awesome!
Sorry that I could not answer on time, but happy you could find a solution.

I'm closing this issue but do not hesitate to re-open it if you feel the need.

Best
