### ISSUE TITLE
why are the subscriber and the client separate classes?

### ISSUE THREAD

**Issue by rodrigodzf** [Cylix/cpp_redis#147]
hi, is there any reason why the subscriber and the client are separate? Aren't they both just clients, wouldn't it make more sense to just have the client with the subscribe method added (or the subscriber inheriting the client)?

**Comment by Cylix** [comment]
Hi,

Yes, it has been designed on purpose.

The main reason is that starting some subscribe related function initiate a different Redis protocol in which all non subscribe commands are denied.
Moreover, the handling of callbacks is different (in the client, callbacks are dismissed when the response is received while subscriber keeps the callback for future published messages).
Finally, it makes it less error prone to mix both subscribe and non-subscribe commands with the two different clients have clearly defined roles.

Inheriting does not change anything as it does not prevent mixing subscribe and non-subscribe commands.

Do you have any concerns with this design?

Best

**Comment by rodrigodzf** [comment]
well, I mainly use the subscriber but I need many of the methods of the client for setting up the connection (mostly client_* functions and some others), I can reimplement these on the subscriber as well, but I find it more simple to have the client have a flag e.g. bSubscribed before the callback is installed, so that the other functions or callbacks are not allowed after this. 
I just would like to have less connections to monitor per instance of my app, right now I have 2 (publisher/subscriber) per instance.

**Comment by rodrigodzf** [comment]
so I just implmented the subscriber subscribe method and the handling in the client and seems to be working fine. If you try to publish after the subscribe you get 
"ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context" from redis which is fine for me since I dont need need to publish after my subscribe. Do you think there will be any other unforeseen consequence?

**Comment by Cylix** [comment]
Hi,

Sorry for the late reply.
You might have some issues by using the subscriber commands on the redis class due to the way callbacks are handled.
Maybe let me know which commands you need to use to setup your subscriber connection, I will consider adding them to the subscriber client if it makes sense :)

Best

**Comment by Cylix** [comment]
I'm closing this issue, but do not hesitate to re-open it if necessary.

Best
