### ISSUE TITLE
ReJSON

### ISSUE THREAD

**Issue by tilmanotto** [Cylix/cpp_redis#151]
Hi Cylix,

I tried several variants with the ReJSON module and cpp_redis. GET and DEL are working fine with the send command, unfortunately I couldn't store data with SET.

Example code:

```
client.send({"JSON.SET", "obj", ".","{\"name\":\"Leonard Cohen\",\"lastSeen\":1478476800,\"loggedOut\": true}'\"}" }, [] (reply & rp) {
  cout << "works fine" << endl;
});
```

I've tried also enclosing JSON with '-character or combining "." with the JSON-string.

The redis-cli command:
`JSON.SET obj . '{"name":"Leonard Cohen","lastSeen":1478476800,"loggedOut": true}'`

JSON example is taken from http://rejson.io/.

Syntax: JSON.SET \<key\> \<path\> \<json\>

Regards,

Tilman

**Comment by tilmanotto** [comment]
Happily this here worked:

client.send({"JSON.SET", "obj", ".","{\"name\":\"Leonard Cohen\",\"lastSeen\":1478476800,\"loggedOut\": true}"}, [] (reply & rp) {
  cout << "result: " << endl << rp;
});

The answer should be "OK".

Perhaps could you assemble a small issue collection for all ReJSON posts? Could be interesting for others.

**Comment by Cylix** [comment]
Hi @tilmanotto ,

Happy that you found a solution and collection ReJSON issues into one place in the wiki is a good idea.
May I ask you more details about your fix, I'm not sure to understand how you solved your issue? Is it in the input parameters (seems like it is not valid c++ code without the escaping) or because you didn't know what was the server response?

Thanks

**Comment by tilmanotto** [comment]
Sorry, the backslahes disappeared in the editor. Sure there should be backslashes before the quotes in the JSON string. For JSON-converting I'm using the very good library of `https://github.com/nlohmann/json.` Makes it very easy dealing with JSON in c++.

**Comment by Cylix** [comment]
Thanks for the details :)
I'm closing this issue then, but feel free to re-open it if you feel the need.

Best
