### ISSUE TITLE
how can support binary data

### ISSUE THREAD

**Issue by qqwx1986** [Cylix/cpp_redis#157]
i want put/get binary data to redis
is it spport?

**Comment by qqwx1986** [comment]
i think i had resolved 
```
struct test
{
int a;
double b;
char c[32];
}
test t;
std::string str((const char*)&t,sizeof(t))

```

**Comment by Cylix** [comment]
Hi,
Yes, that's the way to do it, std::string has a constructor std::string(const char*, size_t size) that allows you to pass arbitrary char* strings, including binary data.

I'm closing this issue but feel free to open a new one or to re-open this one if necessary.

Best
