### ISSUE TITLE
cluster support

### ISSUE THREAD

**Issue by chuengchuenghq** [Cylix/cpp_redis#162]
I would like to know if there is a client cluster support for cpp_redis, or do you have the plan for this feature, because cluster support is very important.

**Comment by Cylix** [comment]
Hi,

There is no support at the moment.
I'd like to develop this support and got that recorded as a major improvement, but unfortunately, I do not have the time to do so as I'm working on other projects that take most of my time. PR are welcome though.

I guess if your top priority is cluster support, you may need to look for other libraries or implement it on top (or within if you wish to PR) cpp_redis.

I'm closing this issue but feel free to re-open if necessary.

Best
