### ISSUE TITLE
Add public reconnect functions to the client and subscriber

### ISSUE THREAD

**Issue by nkochakian** [Cylix/cpp_redis#167]
I have an application that opens several connections to a Redis database, all of which need to be synchronized (they all need to be connected before doing anything.) I noticed that there are situations where one connection will drop and the others won't change states for a while (they sometimes won't detect a disconnection until well after the reconnect delay for the first client has passed.)

It would be helpful if there was an accessible reconnect function so that it would be possible to force every client to disconnect and attempt to reconnect at about the same time.

**Comment by Cylix** [comment]
Hi @nkochakian,

A reconnect function would be the equivalent of a `.disconnect()` followed by a `.connect()`.
If so, I prefer not to provide such a function to avoid possible confusion with `.connect()`.
Or are you looking for a different behavior in the `.reconnect()` function?

Best

**Comment by nkochakian** [comment]
I have decided to manage the connection sequence manually instead of using the automatic reconnect feature
