### ISSUE TITLE
Unprotected member in subscriber during reconnect

### ISSUE THREAD

**Issue by nkochakian** [Cylix/cpp_redis#168]
Before reconnecting, `subscriber::connection_disconnection_handler` acquires a lock ([here](https://github.com/Cylix/cpp_redis/blob/e8eaad32aaa31e4fba50763c93cb68b7dc769932/sources/core/subscriber.cpp#L403)) to prevent access to `m_subscribed_channels`. The corresponding lock for `m_psubscribed_channels` (`m_psubscribed_channels_mutex`) is never acquired. This can cause issues later when `subscriber::re_subscribe` is called, since it modifies `m_psubscribed_channels`.

A side effect of locking the channel map is that the connect callback is called in two different contexts:
1. From `subscriber::connect` with no locks acquired
2. From `subscriber::connection_disconnection_handler` via `subscriber::reconnect` when `m_subscribed_channels_mutex` is locked

For `#`2, calling `subscriber::subscribe` will cause a deadlock. (In the case of Visual C++ 2015, it might actually throw an exception, which is discarded by [this catch all](https://github.com/Cylix/cpp_redis/blob/e8eaad32aaa31e4fba50763c93cb68b7dc769932/sources/core/subscriber.cpp#L464).)

**Comment by Cylix** [comment]
Hi @nkochakian,

Thanks for noticing that and reporting that, I will look into fixing that!

Best

**Comment by Cylix** [comment]
I pushed a fix on master.

Concerning your comment related to the side effect, I did not made any change as of now as it is anyway an existing problem in previous versions, in both redis subscriber and redis client.

I will record that as a possible improvement and work on that when I can.

Best
