### ISSUE TITLE
Multiple definitions do not work when compiling

### ISSUE THREAD

**Issue by cblauvelt** [Cylix/cpp_redis#171]
When multiple optional definitions are defined, each subsequent definition will over write previous definitions.

For example defining `-DUSE_CUSTOM_TCP_CLIENT=1 -DLOGGING_ENABLED=1` will only result in `-D __CPP_REDIS_USE_CUSTOM_TCP_CLIENT=1`

**Comment by Cylix** [comment]
Thanks for fixing that, I'm gonna fix that on tacopie side.
