### ISSUE TITLE
crash when disconnect after commit in windows

### ISSUE THREAD

**Issue by yanwei1983** [Cylix/cpp_redis#24]
tcp_client::disconnect whill call io_service::untrack to erase sock_info, 
but this sock_info may used in io_service::process_io

auto redis_sub = new cpp_redis::redis_subscriber();
redis_sub->psubscribe(xxx);
redis_sub->commit();
delete redis_sub;

**Comment by yanwei1983** [comment]
i think sock_info should delay delete to all io_context is return back

**Comment by Cylix** [comment]
Mmmh, I'm going to look into that as soon as I have some time.
I'm not the developer who wrote the windows port of the library, so might take me a bit more time to go through windows debug.

Thanks again for reporting several issues on windows!

**Comment by Cylix** [comment]
Closing as it is not relevant anymore after the new release v3.0.0 as explained in #39.
