### ISSUE TITLE
`namespace unix` conflicts with `unix` macro

### ISSUE THREAD

**Issue by aardvarkk** [Cylix/cpp_redis#27]
I'm using gcc version 5.4.0 on Ubuntu 16.04 and getting a compiler error on `io_service.cpp` line 24. I believe `unix` is defined as a macro which is throwing the error `expected identifier before numeric constant`.

**Comment by aardvarkk** [comment]
Strangely this problem only seems to manifest itself when I call the cpp_redis CMakeLists.txt from my own CMakeLists.txt via `add_subdirectory()`.

**Comment by aardvarkk** [comment]
I believe my problem is that I had set `set(CMAKE_CXX_STANDARD 11)` in my CMakeLists.txt file. I did this before the call to `add_subdirectory()`. By moving that call below the build of `cpp_redis`, the build seems to work.

**Comment by Cylix** [comment]
Hi,

Thanks for your issue report.
Even though you could fix it, I guess this is still an issue I'm going to look into as soon as I have some time.

unix namespace is indeed maybe not the best namespace name due to these system macros.

**Comment by Cylix** [comment]
Renamed the unix namespace into unix_impl.
Renamed the windows namespace into windows_impl.

This still make sense and should avoid that kind of issue in the future.
