### ISSUE TITLE
API for sorted sets using integers for scores

### ISSUE THREAD

**Issue by fpagliughi** [Cylix/cpp_redis#36]
In Redis, the sorted sets use double-precision floats to represent scores. In the cpp_redis API, these are exposed as integers, such as in this method:

`
redis_client& zremrangebyscore(const std::string& key, int min, int max,
      const reply_callback_t& reply_callback = nullptr);
`

In this case, `min` and `max` should be type `double` instead of `int` to expose the full functionality of the database server. 

This is especially important since Redis is a great means to store time-series data in sorted sets for scientific and real-time applications. Those data sets typically use floating-point timestamps for sub-second precision.

This is a (minor) breaking change in the API.

**Comment by Cylix** [comment]
Hi,

Indeed, I'll have a look into that, thanks for reporting it!

I need to change a bit some underlying stuff (and not just the prototype of the function) since I always considered that the redis server sends me integers.
So, I will double-check the format of the redis protocol in that case and make the appropriate changes.

Best,

**Comment by fpagliughi** [comment]
Sorry, I should have put in references to verify this. It is especially confusing since most of the examples in the Redis documentation use integers for the scores!

In the "Intro to data types", it says:
> every element in a sorted set is associated with a floating point value, called the score ...
https://redis.io/topics/data-types-intro

The documentation for ZADD is more specific:
> Redis sorted sets use a double 64-bit floating point number to represent the score. In all the architectures we support, this is represented as an IEEE 754 floating point number...
https://redis.io/commands/zadd

In every C++ compiler that I have used this corresponds to a type `double`.

**Comment by Cylix** [comment]
Thanks for the link, I'll look into that more deeply tonight.
From what I've seen, I'll have to change a bit the way I retrieve values to support doubles (for now, I'm pretty sure I would report an invalid format from the redis server reply).

**Comment by Cylix** [comment]
Fixed in #45 by adding some overload of the Z** functions with double and string types for min/max/incr parameters.

Changes are non-breaking.
