### ISSUE TITLE
Program hangs up (probably not an issue but a feature request)

### ISSUE THREAD

**Issue by simpuc** [Cylix/cpp_redis#38]
Hello,
if I try to run 
```
int _tmain(int argc, _TCHAR* argv[])
{
	cpp_redis::redis_client client;
	std::cout << "beppe " << std::endl;
	return 0;
}
```
the program prints "beppe" and than hangs up. I think because the running threads do not terminate.
Is it possible to add a function that close all threads and permit the program to terminate?
Thank you
Simone

**Comment by Cylix** [comment]
Thanks for reporting that :)

It should be related to our current network module.
As explained in #29, I'm currently working on a new network module that should solves all these threading issues.
I hope to be able to push the new version by the end of the weekend, but might be take longer (life happens). The unix version is actually ready but I'm waiting to finish the windows port to publish the release.

Best

**Comment by Cylix** [comment]
Closing as it is not relevant anymore after the new release v3.0.0 as explained in #39.
