### ISSUE TITLE
Missing x64 configuration for building

### ISSUE THREAD

**Issue by afrostalin** [Cylix/cpp_redis#40]
cpp_redis 3.0.0 , VS2015 - Missing x64 configuration

**Comment by Cylix** [comment]
Hi,

Could you provide more details about your issue?

I just tried on my side with the following commands:
```bash
cd cpp_redis
mkdir build && cd build
cmake .. -G "Visual Studio 15 2015 Win64"
```

It generates me the appropriate x64 solution and the project builds as expected.

Best

**Comment by afrostalin** [comment]
Yes, all good now, thx. You do very awesome work !)
P.s.
If you use Qt based application with cpp_redis lib you need update : 
cunc_client.hpp,  line 130-131 and 142-143 cnahge parametr name from "slots" to "m_slots" (Qt conflict)
future_client.hpp, line 150-151 and 162-163  cnahge parametr name from "slots" to "m_slots"

I hope this helps someone and can be added in the next commit

Best regards

**Comment by Cylix** [comment]
Awesome then! And glad you enjoy cpp_redis :)

I'll make the changes for a future release, thanks for reporting that.

Best

**Comment by Cylix** [comment]
Fixed by renamed `slots` parameters into `p_slots`.
