### ISSUE TITLE
blpop is blocking?

### ISSUE THREAD

**Issue by simpuc** [Cylix/cpp_redis#41]
Hello,
I am trying to use blpop to implement a queue

I run the program
```
#include "cpp_redis/cpp_redis"

volatile std::atomic_bool should_exit = ATOMIC_VAR_INIT(false);

void
sigint_handler(int) {
	should_exit = true;
}

int main(int argc, _TCHAR* argv[])
{
	cpp_redis::redis_client client;
	client.connect("lx000000010550", 6379, [](cpp_redis::redis_client&) {
		std::cout << "client disconnected (disconnection handler)" << std::endl;
		should_exit = true;
	});

	signal(SIGINT, &sigint_handler);
	while (!should_exit) {
		client.blpop({ "key_queue" }, 0, [](cpp_redis::reply& reply) {
			std::cout << "decrby hello 12: " << reply << std::endl;
		});
		client.commit();
		std::cout << "NEVER STOP" << std::endl;
	}
	client.disconnect();

	return 0;
}
```
It enters in a infinite loop printing "NEVER STOP" and **the CPU load of the computer raises**.
I'd want it block on the instruction 
```
client.blpop({ "key_queue" }, 0, [](cpp_redis::reply& reply) {
			std::cout << "decrby hello 12: " << reply << std::endl;
		});
```
and I'd want to have no CPU load.

Is it possible?

Thank you

Simone

**Comment by Cylix** [comment]
Hi,

Can you try using the `sync_commit` function instead of `commit`?
`.commit()` works asynchronously (it sends the commands, and then your callback is executed while you continue executing your software.
`.sync_commit()` will block until all answers have been received from the redis-server.

Best.

**Comment by Cylix** [comment]
Closing the issue.
If `sync_commit` did not solve the issue, do not hesitate to re-open the issue.
