### ISSUE TITLE
Subscriber + AUTH

### ISSUE THREAD

**Issue by navossoc** [Cylix/cpp_redis#43]
Hi, I have started using this lib yesterday so, I'm still kinda new here...

I'm looking for a way to create a _subscription_ and **auth** at the same time, is that possible?
I made my client (_publisher_) **auth** without any problems, but I can't find any way to **auth** the _subscriber_.

Can someone give me a little help here?

**Comment by Cylix** [comment]
Hi,

Indeed, this is something missing in the current implementation, I have to add the ability to do that.
I'll look into that in the next few days or tomorrow during my few hours of plane flight.

There is still a workaround that consists of using a redis_client and sending the auth command followed by a subscribe command.
That should work, but as the redis_client is not intended for that, you will receive the server notification in raw, as an array. However, it can be enough and reliable as a temporary solution the time to implement the changes (should not take a long time to change).

Anyway, thanks for reporting that!

**Comment by Cylix** [comment]
Hi,

I added a new method to `redis_subscriber`:

```cpp
redis_subscriber& redis_subscriber::auth(const std::string& password, const reply_callback_t& reply_callback);
```

You can use it before calling `subscribe()` or `psubscribe()` to authenticate your subscriber onto the redis-server.

Hope it will solve your issue :)
