### ISSUE TITLE
Link Error in Visual Studio 2015

### ISSUE THREAD

**Issue by ZuroonNotice** [Cylix/cpp_redis#46]
The cpp_redis build is fine in both Debug/Release mode. And I copied the cpp_redis.lib and tacopie.lib to my project folder and referred them in the project setting. I got some link errors when trying to build:

1>tacopie.lib(tcp_socket.obj) : error LNK2019: unresolved external symbol __imp_accept referenced in function "public: class tacopie::tcp_socket __cdecl tacopie::tcp_socket::accept(void)" (?accept@tcp_socket@tacopie@@QEAA?AV12@XZ)
1>tacopie.lib(tcp_socket.obj) : error LNK2019: unresolved external symbol __imp_bind referenced in function "public: void __cdecl tacopie::tcp_socket::bind(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int)" (?bind@tcp_socket@tacopie@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z)
1>tacopie.lib(self_pipe.obj) : error LNK2001: unresolved external symbol __imp_bind
1>tacopie.lib(tcp_socket.obj) : error LNK2019: unresolved external symbol __imp_closesocket referenced in function "public: void __cdecl tacopie::tcp_socket::close(void)" (?close@tcp_socket@tacopie@@QEAAXXZ)
1>tacopie.lib(self_pipe.obj) : error LNK2001: unresolved external symbol __imp_closesocket
1>tacopie.lib(tcp_socket.obj) : error LNK2019: unresolved external symbol __imp_connect referenced in function "public: void __cdecl tacopie::tcp_socket::connect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int)" (?connect@tcp_socket@tacopie@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z)
1>tacopie.lib(self_pipe.obj) : error LNK2001: unresolved external symbol __imp_connect
1>tacopie.lib(tcp_socket.obj) : error LNK2019: unresolved external symbol __imp_htons referenced in function "public: void __cdecl tacopie::tcp_socket::connect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int)" (?connect@tcp_socket@tacopie@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z)
1>tacopie.lib(tcp_socket.obj) : error LNK2019: unresolved external symbol __imp_listen referenced in function "public: void __cdecl tacopie::tcp_socket::listen(unsigned __int64)" (?listen@tcp_socket@tacopie@@QEAAX_K@Z)
1>tacopie.lib(tcp_socket.obj) : error LNK2019: unresolved external symbol __imp_recv referenced in function "public: class std::vector<char,class std::allocator<char> > __cdecl tacopie::tcp_socket::recv(unsigned __int64)" (?recv@tcp_socket@tacopie@@QEAA?AV?$vector@DV?$allocator@D@std@@@std@@_K@Z)
1>tacopie.lib(tcp_socket.obj) : error LNK2019: unresolved external symbol __imp_send referenced in function "public: unsigned __int64 __cdecl tacopie::tcp_socket::send(class std::vector<char,class std::allocator<char> > const &,unsigned __int64)" (?send@tcp_socket@tacopie@@QEAA_KAEBV?$vector@DV?$allocator@D@std@@@std@@_K@Z)
1>tacopie.lib(tcp_socket.obj) : error LNK2019: unresolved external symbol __imp_socket referenced in function "private: void __cdecl tacopie::tcp_socket::create_socket_if_necessary(void)" (?create_socket_if_necessary@tcp_socket@tacopie@@AEAAXXZ)
1>tacopie.lib(self_pipe.obj) : error LNK2001: unresolved external symbol __imp_socket
1>tacopie.lib(tcp_socket.obj) : error LNK2019: unresolved external symbol __imp_getaddrinfo referenced in function "public: void __cdecl tacopie::tcp_socket::connect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int)" (?connect@tcp_socket@tacopie@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z)
1>tacopie.lib(tcp_socket.obj) : error LNK2019: unresolved external symbol __imp_freeaddrinfo referenced in function "public: void __cdecl tacopie::tcp_socket::connect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int)" (?connect@tcp_socket@tacopie@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z)
1>tacopie.lib(io_service.obj) : error LNK2019: unresolved external symbol __imp_WSAPoll referenced in function "private: void __cdecl tacopie::io_service::poll(void)" (?poll@io_service@tacopie@@AEAAXXZ)
1>tacopie.lib(self_pipe.obj) : error LNK2019: unresolved external symbol __imp_ioctlsocket referenced in function "public: __cdecl tacopie::self_pipe::self_pipe(void)" (??0self_pipe@tacopie@@QEAA@XZ)
1>tacopie.lib(self_pipe.obj) : error LNK2019: unresolved external symbol __imp_getsockname referenced in function "public: __cdecl tacopie::self_pipe::self_pipe(void)" (??0self_pipe@tacopie@@QEAA@XZ)
1>tacopie.lib(self_pipe.obj) : error LNK2019: unresolved external symbol __imp_htonl referenced in function "public: __cdecl tacopie::self_pipe::self_pipe(void)" (??0self_pipe@tacopie@@QEAA@XZ)
1>tacopie.lib(self_pipe.obj) : error LNK2019: unresolved external symbol __imp_recvfrom referenced in function "public: void __cdecl tacopie::self_pipe::clr_buffer(void)" (?clr_buffer@self_pipe@tacopie@@QEAAXXZ)
1>tacopie.lib(self_pipe.obj) : error LNK2019: unresolved external symbol __imp_sendto referenced in function "public: void __cdecl tacopie::self_pipe::notify(void)" (?notify@self_pipe@tacopie@@QEAAXXZ)

Are there any dependencies required for building? I am using Visual Studio 2015.

**Comment by ZuroonNotice** [comment]
After some search, I found out I need to add Ws2_32.lib to the library dependency. It ran well in Release mode, but when I ran it in Debug mode, the cpp_redis::client instance crashed with an error:
**fail socket()**
Anyone know why this happened?

**Comment by navossoc** [comment]
You need to initialize WSA first...

Like this:
https://github.com/Cylix/cpp_redis/blob/master/examples/sync_client.cpp#L33-L42

**Comment by ZuroonNotice** [comment]
Thanks! The error was gone and I am using redis_client class.
Now I encountered a new issue now. 
When I called redisClient.commit(), all worked fine. 
But when I use redisClient.sync_commit(), the application is hanging on this method in Debug mode. Please kindly advise. Thanks.

**Comment by Cylix** [comment]
Hi,

Can you provide an example about how you use sync_commit()? That would help me to see if it is a library issue or a lack of documentation concerning how to use it.

Thanks

**Comment by ZuroonNotice** [comment]
I extracted the code snippet and please check. The following code runs well in Release mode but hangs in Debug mode., 
//declared as a class variable
  redis_client redisClient;
        
//logic starts here
        bool needClean = true;
        redisClient.connect(redis_host.c_str(), redis_port);
        redisClient.get(symbol_key, [data,&needClean](reply& reply) {
            if (!reply.is_null())
            {
                if (data->symbol.compare(reply.as_string()) == 0) {
                    needClean = false;
                }
            }
         });
        redisClient.sync_commit();

**Comment by Cylix** [comment]
Hi,

Sorry for the looooog time to treat this issue.
I submitted a new version, v3.4.0, in which tacopie has been updated to be based on `select` instead of `poll` which is basically buggy on windows.

Let's hope this will solve the issue.
Keep me up to date if you have any news.

Best :)

**Comment by Cylix** [comment]
Hi,

A patch was submitted a month ago and no update has been submitted since then.
I close this ticket as the issue seems to be solved (no more complains since patch submission).

Please feel free to re-open it if the problem occurs again in the future.

Best.
