### ISSUE TITLE
How do i convert a cpp_redis::reply to a std::string

### ISSUE THREAD

**Issue by adilbaig** [Cylix/cpp_redis#48]
I have this snippet of code that does not compile.

````
vector<string> rics;
    redis_client.smembers("quote_alerts", [rics](cpp_redis::reply& reply) {
        for(auto r: reply.as_array()) {
            rics.push_back(r);
        }
    });
````

I get the following compile time error 

````
 error: no matching function for call to ‘std::vector<std::__cxx11::basic_string<char> >::push_back(cpp_redis::reply&) const’
             rics.push_back(r);
````

How do I take the response and make a `vector<string>` out of it?

**Comment by Cylix** [comment]
Hi,

`as_array()` returns an array of `cpp_redis::reply`.
You can then extract the underlying value using `as_string` (or `as_integer`, `as_array`, ...).
You can also check for the type of the reply if necessary (`is_string`, `is_integer`, ...).

```cpp
vector<string> rics;
    redis_client.smembers("quote_alerts", [rics](cpp_redis::reply& reply) {
        for(auto r: reply.as_array()) {
            rics.push_back(r.as_string());
        }
    });
```

Technically, the following code should be fine.

You can also learn more about replies [here](https://github.com/Cylix/cpp_redis/wiki/Replies).

Best

**Comment by adilbaig** [comment]
I get this error

````
write-prices2.cpp:46:41: error: passing ‘const std::vector<std::__cxx11::basic_string<char> >’ as ‘this’ argument discards qualifiers [-fpermissive]
             rics.push_back(r.as_string());
                                         ^
````

**Comment by Cylix** [comment]
Hi,

This is because you capture your vector by copy and not by reference inside the lambda.
Can you try with the following code snippet:

```cpp
vector<string> rics;
    redis_client.smembers("quote_alerts", [&rics](cpp_redis::reply& reply) {
        for(auto r: reply.as_array()) {
            rics.push_back(r.as_string());
        }
    });
```

Note the `[&rics]`.

Do not hesitate if you have any other questions.

Best

**Comment by adilbaig** [comment]
Eagle eyes! That was it. Thanks mate.

**Comment by Cylix** [comment]
Awesome!

I'm closing the issue, but feel free to re-open it if necessary.

Best
