### ISSUE TITLE
Redis client hangs when using lrange to get a list

### ISSUE THREAD

**Issue by travisgu** [Cylix/cpp_redis#49]
I am using the lrange command to get part of the values from the a large list (>10M)
 redisClient.lrange(key, start, end,[&](reply& reply) {
  //code logic here
});
If I retrieve 30 or 40 items from the list at one call, the application works fine. 
But if I get more than 40 items such as 500 items, the redis client will hang and the call back is never triggered.  I wonder if there is some internal buffer in the client and if the value exceeds the buffer, the application will hang. 
I am working on Windows and using VisualStudio 2013 with CTP_Nov2013 compiler.

**Comment by Cylix** [comment]
Hi,

Thanks for reporting this issue.
I'll have a look as soon as I can and will come back to you.

Best

**Comment by Cylix** [comment]
Hi,

Sorry for the looooog time to treat this issue.
I submitted a new version, v3.4.0, in which tacopie has been updated to be based on `select` instead of `poll` which is basically buggy on windows.

Let's hope this will solve the issue.
Keep me up to date if you have any news.

Best :)

**Comment by Cylix** [comment]
Hi,

A patch was submitted a month ago and no update has been submitted since then.
I close this ticket as the issue seems to be solved (no more complains since patch submission).

Please feel free to re-open it if the problem occurs again in the future.

Best.
