### ISSUE TITLE
Concurrency issue

### ISSUE THREAD

**Issue by tobbe303** [Cylix/cpp_redis#5]
Having an application using both a redis_client and a redis_subscriber I receive numerous errors from Valgrind when destructing these objects. Possibly have something to do with destroying the redis_connections, but I'm not sure.

The problem can be reproduced by modifying the redis_subscriber example adding an instance of a redis_client and making a connect() on this object. See attached files.

Modified redis_subscriber
[redis_subscriber.cpp.txt](https://github.com/Cylix/cpp_redis/files/47392/redis_subscriber.cpp.txt)

Valgrind output
[valgrind_output.txt](https://github.com/Cylix/cpp_redis/files/47377/valgrind_output.txt)

**Comment by Cylix** [comment]
Thanks for the report and the details. I look at this as soon as possible.

**Comment by Cylix** [comment]
This issue is now patched with #8, mostly by removing the Boost.Asio dependency.
