### ISSUE TITLE
cpp_redis can't correctly handle "Null reply".

### ISSUE THREAD

**Issue by IamYS** [Cylix/cpp_redis#50]
Hi.
I use transactions with redis. 
When using WATCH, EXEC can return a "Null reply" if the execution was aborted. But in this case callback is not triggered.

Steps.
1. Call WATCH for some "key".
2. From other client call SET "key" ...
3. From first app call MULTI and EXEC.
4. Last call of sync_commit() return, but callback for EXEC is not triggered.

Then I have tried to debug cpp_redis and found that it can't process reply like "*-1\r\n".
It throw exception in 
bool array_builder::fetch_array_size(std::string& buffer)

Thanks.

**Comment by Cylix** [comment]
Hi,

Thanks for the issue, I'll make the appropriate changes as soon as possible!

Best

**Comment by Cylix** [comment]
Hi,

This was indeed an incorrect implementation of the protocol on my side.
Array with negative size were considered as invalid replies from the server.

I now pushed a fix which returns a null reply instead.

Please feel free to re-open the issue if necessary.

Best
