### ISSUE TITLE
zrem() without send() in sync_client?

### ISSUE THREAD

**Issue by knadh** [Cylix/cpp_redis#53]
Hey, thanks for the great work.

How'd one do a `send()` with the `sync_client`, for instance, to do a `zrem()` which is not available?

**Comment by Cylix** [comment]
Hi,

Apparently, the `send()` is missing in the sync_client, I'll add that as soon as I can.
Sorry for the inconvenience

Best :)

**Comment by Cylix** [comment]
Hi,

Sorry for the time to process that issue.
I just pushed a commit that provides the send() method to the future and sync clients.

Feel free to reopen this issue if necessary.

Best :)

**Comment by knadh** [comment]
👍 Excellent!
