### ISSUE TITLE
missing callback for mget with 10.000 keys

### ISSUE THREAD

**Issue by wsw2016** [Cylix/cpp_redis#54]
Hello, I'm trying to mget 10.000 entries a 20 bytes long. It works with 3999 values, but not with 4000 - I don't get the call back in this case. The redis-server recieves the call properly.

Example:
void testSetup()
{
    cpp_redis::redis_client client;
    client.connect();
    char key[1000];
    std::string value(20, 'v');
    for (int i = 0; i != 10000; ++i)
    {
        sprintf(key, "k%d", i);
        client.set(key, value);
    }
    client.sync_commit();
    client.disconnect();
}

void testRun()
{
    cpp_redis::redis_client client;
    client.connect();
    char key[1000];
    std::vector<std::string> keys;
    keys.reserve(10000);
    for (int i = 0; i != 10000; ++i)
    {
        sprintf(key, "k%d", i);
        keys.push_back(key);
    }

    client.mget(keys, [] (cpp_redis::reply & reply) {
        if (reply.is_array())
            std::cout << "got " << reply.as_array().size() << " values\n";
    });

    client.commit();
    std::this_thread::sleep_for(std::chrono::seconds(1000));
    client.disconnect();
}

**Comment by Cylix** [comment]
Hi,

Thanks for reporting this issue.
I'll have a look as soon as I can and will come back to you.

This is maybe a similar issue as #49.

Best

**Comment by Cylix** [comment]
Hi,

Sorry for the looooog time to treat this issue.
I submitted a new version, v3.4.0, in which tacopie has been updated to be based on `select` instead of `poll` which is basically buggy on windows.

Let's hope this will solve the issue.
Keep me up to date if you have any news.

Best :)

**Comment by Cylix** [comment]
Hi,

A patch was submitted a month ago and no update has been submitted since then.
I close this ticket as the issue seems to be solved (no more complains since patch submission).

Please feel free to re-open it if the problem occurs again in the future.

Best.
