### ISSUE TITLE
There still appears to be race conditions/hanging when using sync functionality

### ISSUE THREAD

**Issue by potato20** [Cylix/cpp_redis#55]
Using latest version (d0ac8be05f2bd33a0197b40c63fa509bf0ca1b1c). My code is really simple

```
int my_int = 0;
cpp_redis::sync_client sync_redis_client;

//some connection code here

while(true){
  cout << "my_int: " << my_int << endl;
  cpp_redis::reply reply = this->sync_redis_client.get("some_key"); //holds the number 10
  my_int = atoi(reply.as_string().c_str());
}
```

Sometimes when I run the code, I get

```
0
```

sometimes I get

```
0
10
10
...
```

i.e. sometimes it hangs, sometimes it doesn't.

This also happens when i use a regular `redis_client` but call the `sync_commit()` method. This never happens if I run the code async using regular `commit()`;

**Comment by potato20** [comment]
Actually I'm trying out another redis library and I'm getting the same issue. I think the problem is something else.

**Comment by Cylix** [comment]
Hi,

Thanks for reporting that.
I still re-open the issue to investigate and ensure everything is fine on our side.

Best

**Comment by potato20** [comment]
Hey,

So just to confirm, I solved my problem. I was running a multi threaded app and i was sending commands before the client was connected. It's up to you if you want to leave this open.

Thanks,
Potato

**Comment by Cylix** [comment]
Great, I close the issue then!
Thanks for this update :)
