### ISSUE TITLE
Can not find Pipeline examples in tutorial?

### ISSUE THREAD

**Issue by PayneJoe** [Cylix/cpp_redis#56]
Hi there, I landed here as wiki mentioned Pipeline feature in this project, but I did not find examples about that in tutorial. How can I achieve that? Thanks

**Comment by Cylix** [comment]
Hi,

pipelining is automatically supported, you don't need to do anything special.

Basically, when you call any command (.get, .set, ...), the command is not sent but only stored in a buffer.
Then, when you call .commit or .sync_commit, it will flush all the commands together.

So basically, if you want to do pipelining, just execute all your commands and then call commit/sync_commit.

```cpp
.get()
.get()
.get()
.get()
.get()
.get()
.get()
.get()
.commit()
```
Will send everything together.

Does that answer your question?

Best :)

**Comment by PayneJoe** [comment]
Okay, that's what I wanted. Thanks Cylix!

**Comment by Cylix** [comment]
Great!

I'm closing this issue then, but feel free to re-open it if you have any other question :)
