### ISSUE TITLE
Crash when cpp_redis::redis_client is a static variable

### ISSUE THREAD

**Issue by Iridesscent** [Cylix/cpp_redis#61]
There is a <code>std::bad_function_call</code> exception raise when i define <code>cpp_redis::redis_client</code> as a static variable.

The code is quite simple.
```
#include <cpp_redis>
cpp_redis::redis_client client;
int main() {
    return 0;
}
```
I use clion in ubuntu.
Looking forward to your reply.
Thanks.

**Comment by Cylix** [comment]
Hi,

Thanks for your report, I did find the issue and I'm going to submit a patch tonight :)
I'll notify you once it is released.

Best

**Comment by Cylix** [comment]
Fix deployed in version v3.2.1.
Explanations about the reason of the error and code changes are available in #62.

Thanks again for reporting this issue :)

I close the issue but feel free to reopen it if necessary.

Best

**Comment by Iridesscent** [comment]
Huge thanks!!!!

**Comment by wenhuancai** [comment]
@Cylix On win, why did I run into the same problem that the problem has been fixed?
