### ISSUE TITLE
VS2013 Compile error:cpp_redis/network/tcp_client_iface.hpp(41): error C2039: “uint32_t”: not “std” member

### ISSUE THREAD

**Issue by shimachao** [Cylix/cpp_redis#69]
I build the solution  for the x64 platform .
Error info:
cpp_redis/network/tcp_client_iface.hpp(41): error C2039: “uint32_t”: not a member of “std”

**Comment by Cylix** [comment]
Hi,

Thank you for reporting that issue!
I just pushed a fix in which I included cstdint inside tcp_client_iface.hpp.

I'm closing this issue but feel free to reopen it if necessary.

Best :)
