### ISSUE TITLE
No reply when reconnection completed.

### ISSUE THREAD

**Issue by xiaoluffy** [Cylix/cpp_redis#70]
I tried a simple reconnection in callback of client connect:

```cpp
void RedisSender::connect() {
    try {
      this->client->connect(this->host, this->port, [this](cpp_redis::redis_client&) {
        LOG(WARNING) << "Redis disconnected, reconnecting..." << endl;
        this_thread::sleep_for(chrono::seconds(1));
        if((++ this->retries) < RECONNECT_RETRIES)
            this->connect();
      });
      
      if(this->auth.length() > 0)
        this->client->auth(this->auth, [](cpp_redis::reply& reply) {
          if(string("OK").compare(reply.as_string()) != 0)
              LOG(FATAL) << "Redis client authenticated failed.";
      });
      
      this->client->select(this->db, [](cpp_redis::reply& reply) {
          if(string("OK").compare(reply.as_string()) != 0)
              LOG(FATAL) << "Redis client select db failed.";
      });
      
      LOG(INFO) << "Redis client connected to " << this->host << ":" << this->port << "/" << this->db;
      this->client->commit();
    }
    catch(exception &e) {
        LOG(ERROR) << "Redis client connected failed with " << e.what();
        this_thread::sleep_for(chrono::seconds(1));
        if((++ this->retries) < RECONNECT_RETRIES)
            this->connect();
    }
}

// and a loop for test:
void RedisSender::test(string key, string value) {
    try{
        this->client->set(key, value);    
        this->client->get(key, [](cpp_redis::reply& reply) {
            LOG(INFO) << "get hello: " << reply;
        });
        LOG(WARNING) << "test " << value;
        this->client->commit();
    }
    catch(exception &e) {
        this_thread::sleep_for(chrono::seconds(1));
        LOG(WARNING) << "failed ";
    }
}
```

Then I restat the redis-server, after the reconnection successfully completed, no reply such as  "get hello: xx" outputs, but "set" command just work fine!
so how should I fix this issue.

**Comment by Cylix** [comment]
Hi,

Sorry for the time to reply.
I had a look during the past hour and there is indeed something not OK.
Actually, your .set() does not work and I guess both commands are never executed.

I think there is an issue coming from the socket file descriptor used after the disconnection.
I bet it either does not poll the new one or keep using the old one.

I tried to call .disconnect from the disconnection handler to force the cleanup but it didnt solve the issue, so I'll have to give a more in-depth look.

I'll try to fix that ASAP.

Best

**Comment by Cylix** [comment]
Hi,

Just to let you know I fixed the issue and release the fix under v3.5.1 (currently on master branch).
I close the issue but feel free to re-open it if there is still something wrong.

Thanks again for reporting this issue and making cpp_redis better :)

Best

**Comment by xiaoluffy** [comment]
Hi Cylix, I tried to run the same code, and all goes well! Thanks a lot~!

**Comment by Cylix** [comment]
Awesome!
