### ISSUE TITLE
CMake issues under windows

### ISSUE THREAD

**Issue by sedapsfognik** [Cylix/cpp_redis#71]
Hello, guys :)

Thanks for your nice library!
I want to point some bugs I faced while generating VS projects from CMakeLists.txt.

1. On this page: https://github.com/Cylix/cpp_redis/wiki/Compilation-and-installation-options you are saying:

"You can use the MSVC_RUNTIME_LIBRARY_CONFIG Cmake variable to override this setting and choose the Runtime Library of your choice (/MT, /MD, /MTd, /MDd, ...)."

As I understand, only /MT and /MD are applicable, as /MTd and /MDd will automatically apply to Debug versions accordingly. Using /MTd will cause /MTd for Release and /MTdd for Debug.

2. After I changed MSVC_RUNTIME_LIBRARY_CONFIG to /MD I faced another problem:

This config is applied only to cpp_redis library, but not to tacopie. Since I need to link both libraries, I would prefer both of them build with the same MSVC_RUNTIME_LIBRARY_CONFIG flag.

Something like this, but with OS check, as for Linux we do not care about this flag:

IF (NOT USE_CUSTOM_TCP_CLIENT)
  ExternalProject_Add("tacopie"
                      GIT_SUBMODULES ""
                      CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${PROJECT_SOURCE_DIR}/deps"
                      **CMAKE_ARGS "-DMSVC_RUNTIME_LIBRARY_CONFIG=${MSVC_RUNTIME_LIBRARY_CONFIG}"**
                      SOURCE_DIR "${PROJECT_SOURCE_DIR}/tacopie")
ENDIF (NOT USE_CUSTOM_TCP_CLIENT)

3. After VS projects generated, one of *.cpp files won't compile because of it's extra-large *.obj file. One additional argument should be passed to VS compiler: /bigobj.

4. Minor one: please, mention on your Wiki page, that for correct x64 platform(which is mainstream nowadays) we need to force generator to e. g. "cmake . -G "Visual Studio 15 2017 Win64". Without forcing, user will receive projects with both x86 and x64 platform configurations, but x64 ones will be broken(wrong machine types in configurations and others).

That's it :)

**Comment by Cylix** [comment]
Hi,

Awesome!
Really thanks a lot for your ticket. I'm definitely not an expert of windows environment as I spend 99.9999% of my time developing under *nix platforms.

I'll try to integrate the change by the end of this week-end :)

Again thanks a lot for opening this issue, I appreciate a lot!

Best

**Comment by Cylix** [comment]
Hi,

I made small changes in the CMakelist to forward the runtime configuration to tacopie and compile with /bigobj.

I looked a bit about the downside of compiling with `/bigobj`, and it appears that the only drawback is about compatibility issues with MSVC++ linkers older than MSVC++ 2005.
In my opinion, this is already a quite old version, so I decided to enforce `/bigobj` for now.
I will add the ability to disable that option if some people complain about it in the future, but I think we should be good.

I've also updated the documentation concerning the points you mention in this issue.

I close this issue, but please do not hesitate to re-open it if you have any other issues/questions/suggestions :)

Thanks again for opening this issue!

Best
