### ISSUE TITLE
CPU pegged at 100% when use redis_subscriber.connect

### ISSUE THREAD

**Issue by RobWillis** [Cylix/cpp_redis#75]
Just wanted to start with - great library!!

I'm currently using the redis_subscriber to receive notifications.  My use case is very simple - I get a notification, I record a timestamp.  Notifications are very rare.
However, I was noticing my program was often consuming 100% of 1 CPU (kernel space) - after it started and before I put any load or actually received any notifications.

Program worked fine when - just the 1 CPU was pegged.  After much narrowing, I've narrowed it down to the redis_subscriber.connect triggers the issue.

Also, it appears the issue always happens when I run on a single-CPU Ubuntu 16 VM.  On a Ubuntu VM with more than 1 CPU, the issue is much less common (though it does happen). 

The code is pretty straight forward:

    void
    CacheSubscriber::State::initConnection()
    {
        this->doConnInit = false;
        updateCacheTime();
        this->subscriber.connect( this->hostname, this->port, [this](redis_subscriber& sub)
        {
            if ( !this->shutdown )   {  this->doConnInit = true;    }
        });
        this->subscriber.subscribe( this->channel, [this](const std::string& channel, const std::string& msg)
        {
            if ( this->channel == channel )   {  updateCacheTime();   }
        });

        this->subscriber.commit();
    }

If there is any additional info I can provide - let me know...

**Comment by sedapsfognik** [comment]
Have exactly the same issue. All is working fine on Windows on 4 cores, but I get 100% CPU usage on on a single-CPU Ubuntu 16 too. Looks, like subscriber waits in an infinite loop instead of using condition variable.

**Comment by Cylix** [comment]
Hi,

Sorry for the lack of response and thanks for the update.

I'll setup a 1 core VM and will try to investigate on that issue as soon as possible.

Basically, right now, there should be two workers thread: one that does the select/poll and another one that process the read and write callbacks.
Technically, both of them should sleep most of the time.
Having multiple threads on one core should not be an issue.
But my guess is that maybe the kernel switches the thread that owns the CPU such that the select/poll thread is forced to be awake while there is no action to process resulting in high CPU usage.

This is only a guess, so I still have to investigate.

At the moment, the timeout of the select/poll is set to -1, so unlimited sleep until an action occurs. If my guess reveals to be true, then I will consider to either allow the client to customize this timeout or to detect the number of cores and switch to a defined timeout (> 0) in the case of a single core machine.

Best :)
