### ISSUE TITLE
some problems about redis cluster

### ISSUE THREAD

**Issue by SixHe1412** [Cylix/cpp_redis#88]

**Comment by SixHe1412** [comment]
cpp_redis can connect to redis cluster ?

**Comment by Cylix** [comment]
Hi,

cpp_redis supports only the cluster control commands but does not support any other features related to clusters.
I'd like to provide such support, but I currently lack of time to implement it, so I can't give you any hint about when would the library support it.

I'm closing this issue, but feel free to reopen it if necessary and let me know if you have any other questions!

Best :)
