### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by YiuRULE** [Cylix/cpp_redis#90]
I'm working for a new feature on cpp_redis and I saw a little small detail, but it seem that the `CONTRIBUTING.md` file is outdated, the file has a mention of `install_deps.sh` who is seem that the file doesn't exist on the current version of the repository.

Nothing that much important (the project can be build correctly using Ubuntu 16.04 without any problem, at least on my computer) but does the project has hidden dependencies ? if yes maybe we should update the file. :)

**Comment by Cylix** [comment]
Hi,

thanks for reporting this, I just updated the document.

install_deps was originally a script aiming to install dependencies such as google_test or boost asio.
google_test dependency is now handled by cmake and boost asio is no longer used (it has been replaced by tacopie, which is an optional dependency handled by cmake).

Best!
