### ISSUE TITLE
Doesn't build due to dependency on tacopie

### ISSUE THREAD

**Issue by pfultz2** [Cylix/cpp_redis#92]
I download the source tarball from the release, [here](https://github.com/Cylix/cpp_redis/archive/3.5.3.tar.gz), and I get this error:
```
CMake Error at CMakeLists.txt:193 (add_subdirectory):
  The source directory

    /home/paul/tmp/cget/cget/build/tmp-cfe053982ee045be8bbfe32e2c3365d9/cpp_redis-3.5.3/tacopie

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

It seems it relies on the tacopie being there, which is not included in the release tarball. However, even if it were included, I would prefer not to download and build it a second time if I already have tacopie installed. Ultimately, it should look for an installed version and then use the git submodule as a backup.

**Comment by zodiac403** [comment]
@pfultz2 
Right now I am struggling with similar issues. Did you update the git submodule as described [here](https://github.com/Cylix/cpp_redis/wiki/Windows-Install#compiling-and-installing)?

~~~sh
# Get tacopie submodule
git submodule init && git submodule update
~~~

**Comment by Cylix** [comment]
Hi,

Sorry for the late answer.
That's an interesting problem actually, I never tried to install cpp_redis from the tarball.
Technically, tacopie is a submodule of cpp_redis and you need to run `git submodule init` followed `git submodule update`.
Seems like the tarball does not really include anything though, which is a real issue.
I'll try to find a solution, but for now, the only working way would be to clone the repository and to initialize the tacopie sub module as described in the [installation wiki](https://github.com/Cylix/cpp_redis/wiki/Mac-&-Linux-Install).

Please let me know if you have any other questions,

Best!

**Comment by pfultz2** [comment]
> Seems like the tarball does not really include anything though, which is a real issue.

The real issue is that it won't use the tacopie that I already installed. The cmake should do `find_path(TACOPIE_INCLUDE_DIR tacopie/tacopie PATHS ${PROJECT_SOURCE_DIR}/tacopie/includes/)` and use that for the include. Let me try to send a PR.

**Comment by Cylix** [comment]
Just quick update concerning the tarball+no tacopie inside.
This one, I will not be able to do any improvement as it is a Github related issue.
After doing some searches seems like there is no way except waiting for some support from Github in the future.

Best
