### ISSUE TITLE
vcpkg includes missing network folder

### ISSUE THREAD

**Issue by dalebrubaker** [Cylix/cpp_redis#94]
I installed cpp_redis using vcpkg on windows. The includes directory generated doesn't include the cpp_redis file or the network folder, so the lines like #include <cpp_redis/network/redis_connection.hpp>
 in redis_client.hpp failed to compile.

**Comment by Cylix** [comment]
Hi,

I never used vcpkg and was not aware you could actually install cpp_redis with it.
I'm gonna check if there is some configuration file I have to push on the repository to make it work.

Thanks for reporting this issue!

Best

**Comment by Cylix** [comment]
Hi,

Thanks for opening this ticket.
Unfortunately, I do not have the time to set up this and to maintain it.
Furthermore, there are plenty of package manager, so it is pretty hard to figure out which out should be officially supported, and which shouldn't.

However, you, or any other person interested, are free to set it up and to push me a PR, I would be happy to merge it.

Thanks

**Comment by ras0219-msft** [comment]
This looks fixed in the current master of vcpkg (`cpp-redis` package version 3.5.2-2).
