### ISSUE TITLE
Can you  provide more  detailed  redis client  api？  

### ISSUE THREAD

**Issue by Dr13am** [Cylix/cpp_redis#96]
Your official website client API too little ，I have encountered a lot of problems when I use it。

**Comment by Cylix** [comment]
Hi,

Sorry that you encountered some issues while trying to use cpp_redis.
I'm not sure to get what problems did you encountered though? Is it some lack of documentation that made it hard to use the library? Or is it some bugs in the library itself?
Would you mind providing some example such that I could understand your issue more clearly?

Thanks :)

**Comment by Cylix** [comment]
In the absence of a reply, I close this issue.
Feel free to re-open it later if necessary though.

Best
