### ISSUE TITLE
A problem of parameter type in command redis_client::zadd()

### ISSUE THREAD

**Issue by guanhonly** [Cylix/cpp_redis#99]
When I read the Wiki , I saw there are two parameters in command zadd :
const std::vector<std::string> options , const std::map<std::string,std::string> score_member
At first I was confused that why were these two parameters constants instead of const reference , I thought it must be wrong in Wiki.So I have made a test:

redis_client m_client;
std::vector<string> options{"NX"};
std::map<std::string,std::string> m1;
m1.insert({"0","a"},{"1","b"});
m_client.connect();
m_client.zadd("test:1",options,m1);

Compile successful,so I think the type of these two parameters are const reference instead of const.

**Comment by Cylix** [comment]
Good catch, this should indeed be `const&` and not `const`.
I'll submit a fix, thanks!

**Comment by Cylix** [comment]
Should be fixed now, please let me know if you have any other issues!
Best
